       CBL PGMNAME(LONGMIXED) NODLL NOEXPORTALL
      ******************************************************************
      * Copyright IBM Corp. 2025
      *
      * Licensed under the Apache License, Version 2.0 (the "License");
      * you may not use this file except in compliance with the License.
      * You may obtain a copy of the License at
      * 
      *     http://www.apache.org/licenses/LICENSE-2.0
      * 
      * Unless required by applicable law or agreed to in writing
      * , software distributed under the License is distributed on an 
      * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
      * either express or implied. See the License for the specific 
      * language governing permissions and limitations under the
      * License.
      ******************************************************************
      * MAIN PROGRAM IXYJS2CP
      ******************************************************************
      * This is a Data Transform Utility generated module
      * This module is used in 64 bit addressing mode application to
      * convert the Json Message to Cobol Copybook format.
      * This is done using the consumer snippet IXYCNJSN and IXYCASC
      * generated by the Data Transformation Utility.
      ******************************************************************
       IDENTIFICATION DIVISION.
        PROGRAM-ID. 'IXYJS2CP'.

       DATA DIVISION.
        LINKAGE SECTION.
         COPY IXYCASC.

         COPY IXYVARSN.

       PROCEDURE DIVISION USING JSON-DATA
                          RETURNING EVENT-DATA.

           DISPLAY "CALLING AMODE 31 JSON TO COBOL MODULE"

           INITIALIZE EVENT-DATA

           COPY IXYCNJSN.

           GOBACK.

       END PROGRAM 'IXYJS2CP'.